version: "3.9"

services:
  web:
    build: .
    command: >
      sh -c "
      ls
      && npm install
      && npm run start:dev
      "
    volumes:
      - .:/usr/src/app/
    ports:
      - "3000:3000"
    env_file:
      - ./.env